Link to Synops PDF
WildCodeSchool/orleans-0919-php-synops pull request #101
Opened 2020-01-02 16:03 UTC by limoliphi

Link to download (home page)

2020-01-02 16:06 UTC, Niagaraa approved these changes

2020-01-02 16:40 UTC, sblondeau requested changes

2020-01-02 16:40 UTC, sblondeau commented on templates/home/_engagements.html.twig
> +                        <a href="{{ asset('build/images/plaquette.pdf') }}"><i class="fas fa-file-pdf text-danger"></i></a>
fais plutot un dossier files ou documents ou pdf, mais ce n'est pas une image ;-)

2020-01-02 17:40 UTC, Willou-bob approved these changes

2020-01-03 11:28 UTC, sblondeau approved these changes

2020-01-03 11:28 UTC, merged