S03 us25 inscription
WildCodeSchool/orleans-0919-php-synops pull request #103
Opened 2020-01-02 16:49 UTC by AlexandreCln

2020-01-02 17:38 UTC, limoliphi approved these changes

2020-01-03 11:51 UTC, sblondeau requested changes

2020-01-03 11:51 UTC, sblondeau commented on src/Form/RegistrationFormType.php
> +            ->add('email')
EmailType

2020-01-03 11:51 UTC, sblondeau commented on src/Form/RegistrationFormType.php
> +            ->add('password', PasswordType::class)
sur le form de registration, ça peut etre intéressant d'utiliser un RepeatedType
https://symfony.com/doc/current/reference/forms/types/repeated.html

2020-01-03 15:12 UTC, limoliphi approved these changes

2020-01-06 08:42 UTC, sblondeau approved these changes

2020-01-06 08:42 UTC, merged