boucle render navbar
WildCodeSchool/orleans-0919-php-synops pull request #159
Opened 2020-01-09 16:19 UTC by Niagaraa

2020-01-09 16:30 UTC, limoliphi approved these changes

2020-01-09 21:35 UTC, sblondeau requested changes

2020-01-09 21:35 UTC, sblondeau commented on src/Controller/HomeController.php
> +        $categories = $categoryRepository->findAll();
elle sont pas ordonéées alphabétiquement ?

2020-01-10 08:25 UTC, sblondeau approved these changes

2020-01-10 08:25 UTC, merged