US 42 - Admin validate member
WildCodeSchool/orleans-0919-php-synops pull request #162
Opened 2020-01-09 17:14 UTC by AlexandreCln

2020-01-09 17:37 UTC, limoliphi approved these changes

2020-01-09 21:39 UTC, sblondeau requested changes

2020-01-09 21:39 UTC, sblondeau commented on templates/admin_member/index.html.twig
> +                            <form action="{{ url('admin_validate_member', { id: user.id }) }}" method="post">
path() plutot ?

2020-01-09 21:39 UTC, sblondeau commented on src/Controller/AdminUserController.php
> +     * @Route("/valider-membre/{id}", name="admin_validate_member", methods={"POST"})
il manque un @isGranted ROLE_ADMIN pour s'assurer que seuls les admins peuvent effectuer cette action ! très important !

2020-01-10 08:34 UTC, limoliphi approved these changes

2020-01-10 08:50 UTC, limoliphi approved these changes

2020-01-10 08:52 UTC, sblondeau approved these changes

2020-01-10 08:52 UTC, merged