quand faire appel à Syn'ops ?
WildCodeSchool/orleans-0919-php-synops pull request #20
Opened 2019-12-03 16:52 UTC by Niagaraa

2019-12-03 17:21 UTC, AlexandreCln approved these changes

2019-12-03 17:21 UTC, AlexandreCln commented on assets/scss/home.scss
> +    color: #ffffff;
oubli de variable

2019-12-04 08:25 UTC, sblondeau requested changes

2019-12-04 08:25 UTC, sblondeau commented on templates/home/call.html.twig
> +    <div class="container">
balise `<section>` plutot

2019-12-04 08:25 UTC, sblondeau commented on templates/home/call.html.twig
> +                            A n’importe quel moment de votre vie d’entrepreneur, dès lors que vous souhaitez vous
À (majuscule accentuée)

2019-12-04 08:33 UTC, AlexandreCln approved these changes

2019-12-04 08:36 UTC, sblondeau approved these changes

2019-12-04 08:36 UTC, merged