upload partners
WildCodeSchool/orleans-0919-php-synops pull request #217
Opened 2020-01-16 15:14 UTC by limoliphi

2020-01-16 16:56 UTC, Niagaraa approved these changes

2020-01-17 08:13 UTC, sblondeau requested changes

2020-01-17 08:13 UTC, sblondeau commented on src/Entity/Partner.php
> +     *     maxSize="5M",
2M plutot, voire moins

2020-01-17 08:34 UTC, sblondeau approved these changes

2020-01-17 08:34 UTC, merged