index admin section
WildCodeSchool/orleans-0919-php-synops pull request #228
Opened 2020-01-19 19:02 UTC by limoliphi

2020-01-19 20:17 UTC, Niagaraa approved these changes

2020-01-20 00:22 UTC, sblondeau requested changes

2020-01-20 00:22 UTC, sblondeau commented on templates/admin_section/index.html.twig
> +                <tr>
tu as un bout de tableau qui sort de nulle part, mauvais copier coller ?

2020-01-20 08:27 UTC, sblondeau approved these changes

2020-01-20 08:27 UTC, merged