S01 us24 carousel
WildCodeSchool/orleans-0919-php-synops pull request #26
Opened 2019-12-04 13:46 UTC by Willou-bob

2019-12-04 14:43 UTC, limoliphi approved these changes

2019-12-04 14:50 UTC, sblondeau requested changes
certaines images sont trop volumineuse

2019-12-04 14:50 UTC, sblondeau commented on assets/scss/carousel.scss
> +@media (max-width: 768px) {
non pas de media query pour ça, et pas d'utilisation d'id dans le CSS
il faut que tu utilise les classes bootstrap d-taille-none par ex (voir la doc)

2019-12-04 15:57 UTC, limoliphi approved these changes

2019-12-04 16:48 UTC, sblondeau requested changes
quelques images un peu trop grosses

2019-12-04 17:28 UTC, limoliphi approved these changes

2019-12-04 22:00 UTC, sblondeau requested changes
image du bateau tjs trop grosse (pas plus de 100-200ko)

2019-12-05 14:16 UTC, Niagaraa approved these changes

2019-12-05 21:50 UTC, sblondeau approved these changes

2019-12-05 21:50 UTC, merged