Fix affichage section article OK
WildCodeSchool/orleans-0919-php-synops pull request #261
Opened 2020-01-21 12:48 UTC by limoliphi

2020-01-21 13:44 UTC, AlexandreCln approved these changes

2020-01-21 14:52 UTC, sblondeau approved these changes

2020-01-21 14:54 UTC, sblondeau requested changes

2020-01-21 14:54 UTC, sblondeau commented on templates/home/_article.html.twig
>                              <p class="card-text">{{ article.content|truncate(250,true)|raw }}</p>
non il ça risque de truncate au milieu d'une balise html si tu fais ça... vaudrait mieux faire une article.content|striptag|truncate je pense

2020-01-21 16:46 UTC, AlexandreCln approved these changes

2020-01-22 09:34 UTC, sblondeau approved these changes

2020-01-22 09:34 UTC, merged