S01 us20 navbar
WildCodeSchool/orleans-0919-php-synops pull request #28
Opened 2019-12-04 15:03 UTC by AlexandreCln

2019-12-04 15:33 UTC, limoliphi approved these changes

2019-12-04 16:54 UTC, sblondeau requested changes

2019-12-04 16:54 UTC, sblondeau commented on assets/scss/navbar_style.scss
> +@media screen and (min-width: 768px) {
pourquoi  tant de media queries ? :'( 
je suis sur que tu peux t'en passer ;-)

2019-12-05 17:20 UTC, AlexandreCln commented on assets/scss/navbar_style.scss
> +@media screen and (min-width: 768px) {
J'ai pu enlever celui pour la typo responsive et la disparition du logo. Mais pour l'effet en hover des boutton en desktop, je ne voit pas comment m'en passer simplement

2019-12-05 17:26 UTC, korede77 approved these changes

2019-12-05 21:58 UTC, sblondeau approved these changes

2019-12-05 21:58 UTC, merged