S01 us21 footer
WildCodeSchool/orleans-0919-php-synops pull request #31
Opened 2019-12-05 11:02 UTC by korede77

footet done

2019-12-05 11:12 UTC, Niagaraa commented on assets/scss/footer.scss
> +.row {
Donne un nom plus précis à la classe ou imbrique-là (SCSS)

2019-12-05 11:13 UTC, Niagaraa commented on assets/scss/footer.scss
> +    border-bottom: solid 1px $light-color;
Soit il y a une bordure, soit il n'y en a pas

2019-12-05 11:15 UTC, Niagaraa commented on assets/scss/footer.scss
> +}
Répétitif si tu as déjà un text-center dans le HTML avec Bootstrap, choisi

2019-12-05 11:16 UTC, Niagaraa commented on templates/layout.html.twig
> +    <!-- include fichier _footer.html.twig -->
Tu as as ton include, tu peux retirer le commentaire

2019-12-05 11:18 UTC, Niagaraa requested changes

2019-12-05 11:18 UTC, Niagaraa commented on assets/scss/footer.scss
> +}
Répétitif si tu as déjà un text-center dans le HTML avec Bootstrap, choisi

2019-12-05 11:18 UTC, Niagaraa commented on assets/scss/footer.scss
> +    border-bottom: solid 1px $light-color;
Donne un nom plus précis à la classe ou imbrique-là (SCSS)

2019-12-05 11:18 UTC, Niagaraa commented on assets/scss/footer.scss
> +    border-bottom: solid 1px $light-color;
Soit il y a une bordure, soit il n'y en a pas

2019-12-05 17:10 UTC, Niagaraa approved these changes

2019-12-05 21:57 UTC, sblondeau requested changes

2019-12-05 21:57 UTC, sblondeau commented on templates/home/_footer.html.twig
> +                    <div class="infos">
utilise une balise HTML `address`
https://developer.mozilla.org/fr/docs/Web/HTML/Element/address

2019-12-06 07:55 UTC, sblondeau requested changes

2019-12-06 07:55 UTC, sblondeau commented on templates/home/_footer.html.twig
> +                    <adress>
ad**d**ress ! avec 2 D

2019-12-06 08:27 UTC, Niagaraa approved these changes

2019-12-06 08:48 UTC, sblondeau approved these changes

2019-12-06 08:48 UTC, merged