S02 us09 partners add
WildCodeSchool/orleans-0919-php-synops pull request #54
Opened 2019-12-10 16:59 UTC by AlexandreCln

2019-12-10 17:19 UTC, korede77 approved these changes

2019-12-11 08:22 UTC, sblondeau requested changes

2019-12-11 08:22 UTC, sblondeau commented on src/Entity/Partner.php
> +    private $id;
fais les assert en meme temps que le add

2019-12-11 08:22 UTC, sblondeau commented on src/Form/PartnerType.php
> +            ->add('name', null, ['label' => 'Nom'])
plutot que "null" précise le type de champ que tu souhaite. TextType, UrlType, etc.

2019-12-11 08:22 UTC, sblondeau commented on src/Repository/PartnerRepository.php
> +    public function findByExampleField($value)
enlève le code commenté (meme si généré par Sf)

2019-12-11 11:06 UTC, korede77 approved these changes

2019-12-11 11:25 UTC, korede77 approved these changes

2019-12-11 12:20 UTC, merged