S02 us32 actus
WildCodeSchool/orleans-0919-php-synops pull request #61
Opened 2019-12-11 15:03 UTC by korede77

Affichage liste des articles

2019-12-11 16:15 UTC, limoliphi approved these changes

2019-12-11 22:16 UTC, sblondeau requested changes

2019-12-11 22:16 UTC, sblondeau commented on src/Controller/ArticleController.php
> +        if (!$articles) {
s'il n'y a pas d'article, d'une part je ne veut pas forcément une exception, mais juste un message "Pas d'actualité pour le moment"
donc enlève l'exception qui en plus est en anglais et est un mauvais copié collé car il y a tjs écrit "program"...

2019-12-11 22:16 UTC, sblondeau commented on templates/article/list.html.twig
> +                    {% endfor %}
c'est ici que tu dois rajouter ton else

2019-12-12 08:18 UTC, limoliphi approved these changes

2019-12-12 15:34 UTC, sblondeau requested changes

2019-12-12 15:34 UTC, sblondeau commented on templates/article/list.html.twig
> +                            Pas d'actualités pour le moment.
pas d'actualité pour le moment

2019-12-12 21:15 UTC, merged