Edit part done
WildCodeSchool/orleans-0919-php-synops pull request #64
Opened 2019-12-11 16:51 UTC by AlexandreCln

2019-12-11 17:09 UTC, korede77 approved these changes

2019-12-11 22:19 UTC, sblondeau requested changes

2019-12-11 22:19 UTC, sblondeau commented on src/DataFixtures/PartnerFixtures.php
> +        'LAB\'O' => [
tu te prends trop la tete, tu devrais plutot faire une boucle et utiliser faker pour générer des faux noms de company, des faux link et mettre un placeholder pour les logos

2019-12-12 13:19 UTC, limoliphi approved these changes

2019-12-12 15:36 UTC, sblondeau approved these changes

2019-12-12 15:36 UTC, merged