S02 us33 partners (home)
WildCodeSchool/orleans-0919-php-synops pull request #65
Opened 2019-12-11 17:05 UTC by Niagaraa

2019-12-11 17:11 UTC, korede77 approved these changes

2019-12-11 22:20 UTC, sblondeau requested changes

2019-12-11 22:20 UTC, sblondeau commented on src/Controller/HomeController.php
> +        $partners = $partnerRepository->findAll();
pourquoi avoir fait une constante LIMIT_PARTNERS si tu ne l'utilises pas ?

2019-12-11 22:38 UTC, Niagaraa commented on src/Controller/HomeController.php
> +        $partners = $partnerRepository->findAll();
J'ai oublié de l'enlever :')

2019-12-12 08:17 UTC, sblondeau approved these changes

2019-12-12 08:17 UTC, merged