S01 us26 offres
WildCodeSchool/orleans-0919-php-synops pull request #66
Opened 2019-12-12 16:44 UTC by Willou-bob

2019-12-12 16:55 UTC, korede77 approved these changes

2019-12-12 21:18 UTC, sblondeau requested changes

2019-12-12 21:18 UTC, sblondeau commented on src/Migrations/Version20191205095040.php
> +declare(strict_types=1);
pas de migration pour les projets !

2019-12-12 21:18 UTC, sblondeau commented on src/Migrations/Version20191205100952.php
> +<?php
idem, à enlever

2019-12-12 21:18 UTC, sblondeau commented on src/Repository/CategoryRepository.php
> +    public function findByExampleField($value)
pas de code commenté, meme si c'est généré par symfony ;-)

2019-12-12 21:18 UTC, sblondeau commented on src/Repository/ToolRepository.php
> +    public function findByExampleField($value)
idem

2019-12-13 08:00 UTC, sblondeau requested changes
enlève les fichiers de migrations tjs présents (avec un git rm)

et il me faudrait des fixtures

2019-12-13 09:51 UTC, closed without merging