S02 us34 show
WildCodeSchool/orleans-0919-php-synops pull request #73
Opened 2019-12-13 10:07 UTC by korede77

merge conflict show article

2019-12-13 12:39 UTC, Willou-bob approved these changes

2019-12-13 21:05 UTC, sblondeau requested changes

2019-12-13 21:05 UTC, sblondeau commented on src/Controller/ArticleController.php
> +            ->findOneBy(['title' => $slug]);
non ! ton title n'est pas un slug
ici il faut que tu utilises le paramConverter car le slug est unique
donc un show(Article article) va te faire tout seul le findOne

2019-12-15 19:21 UTC, AlexandreCln approved these changes

2019-12-15 19:22 UTC, AlexandreCln approved these changes

2019-12-16 12:34 UTC, sblondeau approved these changes

2019-12-16 12:34 UTC, merged