S03 us18 Contact Form (fonctionnalité et CSS OK)
WildCodeSchool/orleans-0919-php-synops pull request #87
Opened 2019-12-18 10:12 UTC by limoliphi

Contact form is OK

2019-12-18 10:26 UTC, korede77 approved these changes

2019-12-18 10:51 UTC, sblondeau requested changes

2019-12-18 10:51 UTC, sblondeau commented on src/Entity/Contact.php
> +     * @ORM\Column(type="string", length=255)
non pas de @ORM car tu ne veux pas créé de table Contact en BDD en fait !

2019-12-18 10:51 UTC, sblondeau commented on src/Repository/ContactRepository.php
> +    public function findByExampleField($value)
et pas besoin du Contact Repository non plus

2019-12-18 10:51 UTC, sblondeau commented on templates/contact/index.html.twig
> +    <div class="ContactForm mt-5 container">
pas de majuscule au noms de classe, utilise plutot la syntaxe mon-nom-de-classe (avec des tirets et non du camelCase)

2019-12-23 13:54 UTC, AlexandreCln approved these changes

2019-12-24 10:50 UTC, sblondeau approved these changes

2019-12-24 10:50 UTC, merged