S03 us13 tools
WildCodeSchool/orleans-0919-php-synops pull request #99
Opened 2020-01-02 15:18 UTC by Niagaraa

Les documents pour chaque outil seront affichés lorsque le CRUD outils sera fait

2020-01-02 15:31 UTC, limoliphi approved these changes

2020-01-02 16:39 UTC, sblondeau requested changes

2020-01-02 16:39 UTC, sblondeau commented on templates/tool/index.html.twig
> +                                <p class="ml-5">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto
pas de lorem

2020-01-07 12:53 UTC, sblondeau requested changes

2020-01-07 12:53 UTC, sblondeau commented on templates/_navbar.html.twig
> +                    {% for category in categories %}
nope, il me faut un render() dans le twig, ça évite d'avoir à passer les categories dans tous les controleurs
https://symfony.com/doc/current/templates.html#embedding-controllers

2020-01-07 15:07 UTC, merged